<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>TestingClaude</RootNamespace>
    <AssemblyName>TestingClaude</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="8.0.33" />
  </ItemGroup>

</Project>
